[project]
name = "nanocode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Roshan", email = "roshanpoojary16@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=3.8.0",
    "prompt-toolkit>=3.0.53",
    "requests>=2.34.2",
]

[project.scripts]
nanocode = "nanocode:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
